/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerritoriosRouteImport } from './routes/territorios'
import { Route as SdrRouteImport } from './routes/sdr'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as EtiquetasRouteImport } from './routes/etiquetas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'

const TerritoriosRoute = TerritoriosRouteImport.update({
  id: '/territorios',
  path: '/territorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrRoute = SdrRouteImport.update({
  id: '/sdr',
  path: '/sdr',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetasRoute = EtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimento': typeof AtendimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/etiquetas': typeof EtiquetasRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scripts': typeof ScriptsRoute
  '/sdr': typeof SdrRoute
  '/territorios': typeof TerritoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimento': typeof AtendimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/etiquetas': typeof EtiquetasRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scripts': typeof ScriptsRoute
  '/sdr': typeof SdrRoute
  '/territorios': typeof TerritoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimento': typeof AtendimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/conexoes': typeof ConexoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/etiquetas': typeof EtiquetasRoute
  '/funil': typeof FunilRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/scripts': typeof ScriptsRoute
  '/sdr': typeof SdrRoute
  '/territorios': typeof TerritoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/atendimento'
    | '/campanhas'
    | '/conexoes'
    | '/configuracoes'
    | '/etiquetas'
    | '/funil'
    | '/login'
    | '/relatorios'
    | '/scripts'
    | '/sdr'
    | '/territorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/atendimento'
    | '/campanhas'
    | '/conexoes'
    | '/configuracoes'
    | '/etiquetas'
    | '/funil'
    | '/login'
    | '/relatorios'
    | '/scripts'
    | '/sdr'
    | '/territorios'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/atendimento'
    | '/campanhas'
    | '/conexoes'
    | '/configuracoes'
    | '/etiquetas'
    | '/funil'
    | '/login'
    | '/relatorios'
    | '/scripts'
    | '/sdr'
    | '/territorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AtendimentoRoute: typeof AtendimentoRoute
  CampanhasRoute: typeof CampanhasRoute
  ConexoesRoute: typeof ConexoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EtiquetasRoute: typeof EtiquetasRoute
  FunilRoute: typeof FunilRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ScriptsRoute: typeof ScriptsRoute
  SdrRoute: typeof SdrRoute
  TerritoriosRoute: typeof TerritoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/territorios': {
      id: '/territorios'
      path: '/territorios'
      fullPath: '/territorios'
      preLoaderRoute: typeof TerritoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr': {
      id: '/sdr'
      path: '/sdr'
      fullPath: '/sdr'
      preLoaderRoute: typeof SdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiquetas': {
      id: '/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof EtiquetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  AtendimentoRoute: AtendimentoRoute,
  CampanhasRoute: CampanhasRoute,
  ConexoesRoute: ConexoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EtiquetasRoute: EtiquetasRoute,
  FunilRoute: FunilRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  ScriptsRoute: ScriptsRoute,
  SdrRoute: SdrRoute,
  TerritoriosRoute: TerritoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
